services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env.api
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on: []

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env.bot
    volumes:
      - ./data:/app/data
    depends_on:
      - api